#!/usr/bin/env python3
"""
ATS Call Log Server - Local relay that writes call logs to markdown.
Receives POST requests from Chrome extension and appends entries to a daily markdown file on the desktop.
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path
from http.server import HTTPServer, BaseHTTPRequestHandler
import threading

# Config
PORT = 8765
LOG_DIR = Path.home() / "Desktop" / "ats-call-logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

call_entries = []
analysis_entries = []
lock = threading.Lock()


def get_log_file():
    date_str = datetime.now().strftime("%Y-%m-%d")
    return LOG_DIR / f"call-log-{date_str}.md"


def format_duration(seconds):
    if not seconds:
        return "N/A"
    h, rem = divmod(int(seconds), 3600)
    m, s = divmod(rem, 60)
    if h > 0:
        return f"{h}h {m}m {s}s"
    if m > 0:
        return f"{m}m {s}s"
    return f"{s}s"


def render_markdown():
    lines = []
    lines.append(f"# ATS Call Log - {datetime.now().strftime('%A, %B %d, %Y')}")
    lines.append("")
    lines.append(
        f"*Auto-generated by ATS Automation - Last updated: {datetime.now().strftime('%I:%M:%S %p')}*"
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    if analysis_entries:
        lines.append("## AI Analysis Results")
        lines.append("")
        for entry in analysis_entries:
            lines.append(f"### {entry.get('timestamp', '')}")
            lines.append("")
            phone = entry.get("phone", "Unknown")
            score = entry.get("qualification_score", entry.get("score", "N/A"))
            sentiment = entry.get("sentiment", "N/A")
            disposition = entry.get("suggested_disposition", entry.get("disposition", "N/A"))
            tags = entry.get("tags", [])
            summary = entry.get("summary", "")
            notes = entry.get("salesforce_notes", "")
            state = entry.get("detected_state", "")
            insurance = entry.get("detected_insurance", "")
            duration = entry.get("duration", "")
            client = entry.get("client", "")
            transcript = entry.get("transcription", "")

            score_emoji = (
                "🔴"
                if isinstance(score, (int, float)) and score >= 70
                else ("🟡" if isinstance(score, (int, float)) and score >= 40 else "⚪️")
            )
            direction_emoji = "📥" if entry.get("direction", "").lower() == "inbound" else "📤"

            lines.append(f"**Phone:** {phone} {direction_emoji} | **Client:** {client}")
            lines.append("")
            lines.append(f"| Field | Value |")
            lines.append(f"|-------|-------|")
            lines.append(f"| **Score** | {score_emoji} {score} |")
            lines.append(f"| **Sentiment** | {sentiment} |")
            lines.append(f"| **Disposition** | {disposition} |")
            if state:
                lines.append(f"| **State** | {state} |")
            if insurance:
                lines.append(f"| **Insurance** | {insurance} |")
            if duration:
                lines.append(f"| **Duration** | {format_duration(duration)} |")
            if tags:
                lines.append(f"| **Tags** | {', '.join(tags)} |")
            lines.append("")

            if summary:
                lines.append(f"**Summary:** {summary}")
                lines.append("")

            if notes:
                lines.append(f"**Salesforce Notes:**")
                lines.append(f"```\n{notes}\n```")
                lines.append("")

            if transcript:
                lines.append(f"**Transcript:**")
                lines.append(
                    f"```\n{transcript[:2000]}{'...' if len(transcript) > 2000 else ''}\n```"
                )
                lines.append("")

            lines.append("---")
            lines.append("")

    if call_entries:
        lines.append("## Call Events (Raw)")
        lines.append("")
        lines.append("| Time | Phone | Direction | Client |")
        lines.append("|------|-------|-----------|--------|")
        for entry in call_entries:
            ts = entry.get("timestamp", "")
            phone = entry.get("phone", "Unknown")
            direction = entry.get("direction", "N/A")
            client = entry.get("client", "N/A")
            lines.append(f"| {ts} | {phone} | {direction} | {client} |")
        lines.append("")

    lines.append("---")
    lines.append(
        f"*Total calls logged: {len(call_entries)} | Total analyses: {len(analysis_entries)}*"
    )

    return "\n".join(lines)


def write_log_file():
    content = render_markdown()
    log_file = get_log_file()
    with open(log_file, "w", encoding="utf-8") as f:
        f.write(content)
    return log_file


class Handler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        print(f"[{datetime.now().strftime('%H:%M:%S')}] {format % args}")

    def send_json(self, data, status=200):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode())

    def do_POST(self):
        if self.path == "/api/call-event":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length).decode() if length > 0 else "{}"
            try:
                data = json.loads(body)
                with lock:
                    call_entries.append(
                        {
                            "timestamp": datetime.now().strftime("%I:%M:%S %p"),
                            "phone": data.get("phone", "Unknown"),
                            "direction": data.get("direction", "Unknown"),
                            "client": data.get("client", "flyland"),
                            "event": data.get("event", "call"),
                            "raw": data,
                        }
                    )
                    log_file = write_log_file()
                print(f"[LOG] Call event logged: {data.get('phone', 'Unknown')} -> {log_file.name}")
                self.send_json({"status": "ok", "file": str(log_file)})
            except json.JSONDecodeError:
                self.send_json({"error": "Invalid JSON"}, 400)

        elif self.path == "/api/analysis-result":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length).decode() if length > 0 else "{}"
            try:
                data = json.loads(body)
                with lock:
                    analysis_entries.append(
                        {
                            "timestamp": datetime.now().strftime("%I:%M:%S %p"),
                            "phone": data.get("phone", "Unknown"),
                            "client": data.get("client", "flyland"),
                            "direction": data.get("direction", ""),
                            "qualification_score": data.get(
                                "qualification_score", data.get("score")
                            ),
                            "score": data.get("score"),
                            "sentiment": data.get("sentiment", "neutral"),
                            "suggested_disposition": data.get(
                                "suggested_disposition", data.get("disposition", "N/A")
                            ),
                            "disposition": data.get("disposition"),
                            "tags": data.get("tags", []),
                            "summary": data.get("summary", ""),
                            "salesforce_notes": data.get("salesforce_notes", ""),
                            "detected_state": data.get("detected_state", ""),
                            "detected_insurance": data.get("detected_insurance", ""),
                            "duration": data.get("duration"),
                            "transcription": data.get("transcription", ""),
                            "caller_name": data.get("caller_name", ""),
                            "raw": data,
                        }
                    )
                    log_file = write_log_file()
                print(
                    f"[LOG] Analysis logged: {data.get('phone', 'Unknown')} (score: {data.get('qualification_score', data.get('score', 'N/A'))}) -> {log_file.name}"
                )
                self.send_json({"status": "ok", "file": str(log_file)})
            except json.JSONDecodeError:
                self.send_json({"error": "Invalid JSON"}, 400)

        elif self.path == "/api/status":
            with lock:
                log_file = get_log_file()
            self.send_json(
                {
                    "status": "ok",
                    "running": True,
                    "calls_logged": len(call_entries),
                    "analyses_logged": len(analysis_entries),
                    "log_file": str(log_file),
                    "port": PORT,
                }
            )

        elif self.path == "/api/clear":
            with lock:
                call_entries.clear()
                analysis_entries.clear()
                log_file = write_log_file()
            self.send_json({"status": "cleared", "file": str(log_file)})

        elif self.path == "/api/dump":
            with lock:
                log_file = write_log_file()
            self.send_json(
                {
                    "status": "ok",
                    "file": str(log_file),
                    "calls": len(call_entries),
                    "analyses": len(analysis_entries),
                }
            )

        else:
            self.send_json({"error": "Unknown endpoint"}, 404)

    def do_GET(self):
        if self.path == "/health":
            self.send_json({"status": "ok", "running": True, "port": PORT})
        elif self.path == "/":
            self.send_json(
                {
                    "service": "ATS Call Log Server",
                    "version": "1.0.0",
                    "port": PORT,
                    "endpoints": [
                        "/api/call-event",
                        "/api/analysis-result",
                        "/api/status",
                        "/api/clear",
                        "/api/dump",
                    ],
                }
            )
        else:
            self.send_json({"error": "Not found"}, 404)


def main():
    print(f"""
╔══════════════════════════════════════════════════╗
║         ATS Call Log Server                     ║
║         Local relay for call logging            ║
╠══════════════════════════════════════════════════╣
║  Port:     {PORT}
║  Log dir:  {LOG_DIR}
║  Log file:  call-log-YYYY-MM-DD.md
╠══════════════════════════════════════════════════╣
║  Endpoints:                                   ║
║    POST /api/call-event      - Log call event  ║
║    POST /api/analysis-result - Log AI analysis ║
║    GET  /api/status          - Server status   ║
║    GET  /api/clear           - Clear all logs ║
║    GET  /api/dump            - Force save     ║
╚══════════════════════════════════════════════════╝
""")

    server = HTTPServer(("", PORT), Handler)
    print(f"Server running on http://localhost:{PORT}")
    print(f"Logs will be saved to: {LOG_DIR}")
    print(f'Open log file: open "{LOG_DIR}"')
    print(f"\nPress Ctrl+C to stop\n")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down...")
        server.shutdown()


if __name__ == "__main__":
    main()
