/**
 * Transcription Service
 * Handles call transcription using Web Speech API
 */

class TranscriptionService {
    constructor() {
        this.recognition = null;
        this.isRecording = false;
        this.transcript = '';
        this.onTranscriptUpdate = null;
        this.onError = null;
    }

    // Check if speech recognition is supported
    isSupported() {
        return 'webkitSpeechRecognition' in window || 'SpeechRecognition' in window;
    }

    // Initialize speech recognition
    init() {
        if (!this.isSupported()) {
            ATS.logger.warn('Speech recognition not supported');
            return false;
        }

        const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
        this.recognition = new SpeechRecognition();
        
        this.recognition.continuous = true;
        this.recognition.interimResults = true;
        this.recognition.lang = 'en-US';

        this.recognition.onresult = (event) => {
            let interimTranscript = '';
            
            for (let i = event.resultIndex; i < event.results.length; i++) {
                const transcript = event.results[i][0].transcript;
                
                if (event.results[i].isFinal) {
                    this.transcript += transcript + ' ';
                    ATS.logger.info('★ Final transcript received:', transcript.substring(0, 50));
                    
                    if (this.onTranscriptUpdate) {
                        this.onTranscriptUpdate(this.transcript, true);
                    }
                } else {
                    interimTranscript += transcript;
                    ATS.logger.debug('Interim transcript:', transcript);
                }
            }
        };

        this.recognition.onerror = (event) => {
            ATS.logger.error('★ Speech recognition error:', event.error, event);
            if (this.onError) {
                this.onError(event.error);
            }
        };

        this.recognition.onend = () => {
            this.isRecording = false;
            ATS.logger.info('★ Speech recognition ended, transcript length:', this.transcript.length);
        };

        this.recognition.onstart = () => {
            ATS.logger.info('★ Speech recognition started successfully');
        };

        ATS.logger.info('Transcription service initialized');
        return true;
    }

    // Start recording
    start() {
        ATS.logger.info('★ Transcription start() called');
        
        if (!this.recognition) {
            ATS.logger.info('★ Recognition not initialized, initializing now...');
            this.init();
        }
        
        if (!this.recognition) {
            ATS.logger.error('Cannot start transcription - not initialized');
            return false;
        }

        try {
            this.transcript = '';
            this.recognition.start();
            this.isRecording = true;
            ATS.logger.info('★ Transcription start() successful');
            return true;
        } catch (e) {
            ATS.logger.error('★ Error starting transcription:', e.message, e);
            return false;
        }
    }

    // Stop recording
    stop() {
        if (!this.recognition || !this.isRecording) {
            return;
        }

        try {
            this.recognition.stop();
            this.isRecording = false;
            ATS.logger.info('Transcription stopped');
        } catch (e) {
            ATS.logger.error('Error stopping transcription:', e);
        }
    }

    // Get current transcript
    getTranscript() {
        return this.transcript;
    }

    // Generate markdown from transcript
    generateMarkdown(callData) {
        const markdown = `# Call Transcription - ${new Date().toISOString()}

## Call Info
- **Phone:** ${callData.phoneNumber || 'Unknown'}
- **Caller Name:** ${callData.callerName || 'Unknown'}
- **Status:** ${callData.status || 'Unknown'}
- **Start Time:** ${callData.startTime || 'Unknown'}
- **End Time:** ${new Date().toISOString()}

## Transcription

${this.transcript || 'No transcription available'}

## Notes

---

*Generated by ATS Automation*
`;
        return markdown;
    }

    // Save to markdown file
    saveToMarkdown(callData) {
        const markdown = this.generateMarkdown(callData);
        
        const blob = new Blob([markdown], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        
        const a = document.createElement('a');
        a.href = url;
        a.download = `call_${Date.now()}_${callData.phoneNumber || 'unknown'}.md`;
        a.click();
        
        URL.revokeObjectURL(url);
        
        ATS.logger.info('Transcription saved to markdown');
        
        return markdown;
    }
}

window.TranscriptionService = TranscriptionService;
